<?xml version="1.0" encoding="UTF-8"?><testrun name="SbbApplicationTests" project="sbb" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.mysite.sbb.SbbApplicationTests" time="0.001" displayname="SbbApplicationTests" uniqueid="[engine:junit-jupiter]/[class:com.mysite.sbb.SbbApplicationTests]">
    <testcase name="testJpa" classname="com.mysite.sbb.SbbApplicationTests" time="0.001" displayname="testJpa()" uniqueid="[engine:junit-jupiter]/[class:com.mysite.sbb.SbbApplicationTests]/[method:testJpa()]">
      <error>java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@541897c6 testClass = com.mysite.sbb.SbbApplicationTests, locations = [], classes = [com.mysite.sbb.SbbApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@71def8f8, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@32ee6fee, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@47faa49c, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@66d3eec0, org.springframework.boot.test.context.SpringBootTestAnnotation@2468c27e], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:180)&#13;
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:191)&#13;
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:130)&#13;
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:260)&#13;
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:163)&#13;
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)&#13;
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)&#13;
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)&#13;
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)&#13;
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)&#13;
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)&#13;
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)&#13;
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)&#13;
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)&#13;
	at java.base/java.util.Optional.orElseGet(Optional.java:364)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution [Database may be already in use: "C:/pyochan/workSpace/sbb/newDB.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-224]] [n/a]&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)&#13;
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)&#13;
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1231)&#13;
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:949)&#13;
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)&#13;
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)&#13;
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)&#13;
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)&#13;
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)&#13;
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)&#13;
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1454)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:553)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)&#13;
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)&#13;
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)&#13;
	... 17 more&#13;
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution [Database may be already in use: "C:/pyochan/workSpace/sbb/newDB.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-224]] [n/a]&#13;
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:421)&#13;
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)&#13;
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:364)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)&#13;
	... 38 more&#13;
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to open JDBC Connection for DDL execution [Database may be already in use: "C:/pyochan/workSpace/sbb/newDB.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-224]] [n/a]&#13;
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:51)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:94)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:74)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:39)&#13;
	at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:63)&#13;
	at org.hibernate.tool.schema.extract.spi.ExtractionContext.getQueryResults(ExtractionContext.java:43)&#13;
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:39)&#13;
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:66)&#13;
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.&lt;init&gt;(DatabaseInformationImpl.java:60)&#13;
	at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:185)&#13;
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:98)&#13;
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:286)&#13;
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:145)&#13;
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)&#13;
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:142)&#13;
	at org.hibernate.boot.internal.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:37)&#13;
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)&#13;
	at org.hibernate.internal.SessionFactoryImpl.&lt;init&gt;(SessionFactoryImpl.java:315)&#13;
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:450)&#13;
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1507)&#13;
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75)&#13;
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:388)&#13;
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)&#13;
	... 42 more&#13;
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "C:/pyochan/workSpace/sbb/newDB.mv.db". Possible solutions: close all other connection(s); use the server mode [90020-224]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)&#13;
	at org.h2.message.DbException.get(DbException.java:212)&#13;
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:165)&#13;
	at org.h2.mvstore.db.Store.&lt;init&gt;(Store.java:142)&#13;
	at org.h2.engine.Database.&lt;init&gt;(Database.java:326)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:92)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:222)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:201)&#13;
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:343)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:125)&#13;
	at org.h2.Driver.connect(Driver.java:59)&#13;
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)&#13;
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)&#13;
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)&#13;
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)&#13;
	at com.zaxxer.hikari.pool.HikariPool.&lt;init&gt;(HikariPool.java:100)&#13;
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)&#13;
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)&#13;
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:428)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:46)&#13;
	... 62 more&#13;
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/pyochan/workSpace/sbb/newDB.mv.db [2.2.224/7]&#13;
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)&#13;
	at org.h2.mvstore.SingleFileStore.lockFileChannel(SingleFileStore.java:143)&#13;
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:117)&#13;
	at org.h2.mvstore.SingleFileStore.open(SingleFileStore.java:81)&#13;
	at org.h2.mvstore.MVStore.&lt;init&gt;(MVStore.java:286)&#13;
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2035)&#13;
	at org.h2.mvstore.db.Store.&lt;init&gt;(Store.java:133)&#13;
	... 79 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
